---
- name: Deploy Booksy App
  hosts: booksy_servers
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull frontend Docker image
      docker_image:
        name: oshinibandara2001/devops-frontend
        source: pull

    - name: Pull backend Docker image
      docker_image:
        name: oshinibandara2001/devops-backend
        source: pull

    # ðŸ‘‡ Stop and remove old backend container if exists
    - name: Stop backend container
      docker_container:
        name: booksy-backend
        state: absent

    # ðŸ‘‡ Stop and remove old frontend container if exists
    - name: Stop frontend container
      docker_container:
        name: booksy-frontend
        state: absent

    - name: Run backend container
      docker_container:
        name: booksy-backend
        image: oshinibandara2001/devops-backend:latest
        state: started
        restart_policy: always
        ports:
          - "5000:5000"

    - name: Run frontend container
      docker_container:
        name: booksy-frontend
        image: oshinibandara2001/devops-frontend:latest
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
